.TH fort 8 "2019-10-14" "v1.1.1" "FORT validator"

.SH NAME
fort \- RPKI certificate path validator and RTR server

.SH SYNOPSIS
.B fort
[\fIOPTIONS\fR] 

.SH DESCRIPTION

FORT is an RPKI validator and a RTR server (RTR versions 0 and 1 are
supported).
In the RPKI context, FORT is also known as an RP (Relying Party).
A simple resume of the actions performed by an RP can be read at RFC 6480
section 6
.RI "(" https://tools.ietf.org/html/rfc6480#section-6 ")."
.P
The RTR (RPKI to Router Protocol) is basically "a protocol to deliver validated
prefix origin data to routers", see RFC 6810
.RI "(" https://tools.ietf.org/html/rfc6810 ")"
and RFC 8210
.RI "(" https://tools.ietf.org/html/rfc8210 ")."
.P

So, FORT performs RPKI validations starting from a single or set of TALs (Trust
Anchor Locators), either in a recurrent or single (standalone) way.
Additionally, it can talk to routers using the RTR protocol (version will
depend on the client, both 0 and 1 are supported) to provide them the VRPs
(Validated ROA Payloads) and the BGPsec Router Keys resultant of the
validation.
 
.SH OPTIONS
.TP
.B \-h, \-\-help
.RS 4
Print long usage message and exit.
.RE
.P

.B \-\-usage
.RS 4
Print short usage message and exit.
.RE
.P

.B \-V, \-\-version
.RS 4
Print program version and exit.
.RE
.P

.BR \-f ", " \-\-configuration-file=\fIFILE\fR
.RS 4
Path to a JSON file from where additional configuration will be read.
.P
The configuration options are mostly the same as the ones presented in this
manual. Each property is mapped as a member of the main JSON object, the
members that contain a dot '.' must be set as objects (eg.
"--server.address=127.0.0.1" will be set as "{ "server": { "address":
"127.0.0.1" } }".
.P
An example configuration file can be seen in this manual at the \fBEXAMPLES\fR
section.
.P
Some configuration options can't be set at the JSON configuration file:
\fB--version\fR, \fB--help\fR, \fB--version\fR, and \fB--configuration-file\fR.
.P
Other configuration options can be configured exclusively at the JSON
configuration file:
.P
.B rsync.program
.RS 4
Name of the program needed to invoke an rsync file transfer. The default value
is "rsync".
.RE
.P
.B rsync.arguments-recursive
.RS 4
Arguments needed by
.B rsync.program
to perform a recursive rsync. The arguments are specified as a JSON string
array; its default value is:
[ "--recursive", "--delete", "--times", "--contimeout=20", "$REMOTE", "$LOCAL" ]
.P
FORT will replace "$REMOTE" with the remote URL it needs to download, and
"$LOCAL" with the target local directory where the file is supposed to be
dropped.
.P
If \fBrsync.program\fR set is \fIrsync\fR (default value), see more about its
arguments and behavior at \fIrsync(1)\fR.
.RE
.P
.B rsync.arguments-flat
.RS 4
Arguments needed by
.B rsync.program
to perform a single-file rsync. The arguments are specified as a JSON string
array; its default value is:
[ "--times", "--contimeout=20", "--dirs", "$REMOTE", "$LOCAL" ]
.P
FORT will replace "$REMOTE" with the remote URL it needs to download, and
"$LOCAL" with the target local directory where the file is supposed to be
dropped.
.P
If \fBrsync.program\fR set is \fIrsync\fR (default value), see more about its
arguments and behavior at \fIrsync(1)\fR.
.RE
.P
.B incidences
.RS 4
A listing of actions to be performed by validation upon encountering certain
common error conditions. This configuration is a means to modify FORTs
validator behavior upon encountering profile violations that, from experience,
are often overlooked.
.P
The incidences are configured inside the member "incidences" as a JSON array
of objects, each with two members "name" and "action", eg:
.P
"incidences": [
.RS 2
{
.RS 2
"name": "incid-hashalg-has-params",
.br
"action": "warn"
.RE
}
.RE
]
.P
An incidence contains a \fBname\fR and an \fBaction\fR. The \fBname\fR is
merely an identifier defined by FORT that states a particular error condition,
and the \fBaction\fR is an enumeration that states the outcome of a violation
of the corresponding incidence.
.P
The \fBaction\fR can have one of three values:
.br
.RS 4
\fIerror\fR: Print error message in error log level, fail validation of the
offending object (and all of its children).
.br
\fIwarn\fR: Print error message in warning log level, continue validation as if
nothing happened.
.br
\fIignore\fR: Do not print error message, continue validation as if nothing
happened.
.RE
.P
By default, all the incidences have an action of \fIignore\fR. Currently there's
only one registered incidence:
\fIincid-hashalg-has-params\fR (Signed Object's hash algorithm has NULL object
as parameters).
.P
More information about incidences can be consulted at FORT's web docs.
.RE
.RE
.P

.BR \-t ", " \-\-tal=(\fIFILE\fR|\fIDIRECTORY\fR)
.RS 4
Path to the TAL file or directory the validation will sprawl from.
.P
If a DIRECTORY is specified, the files with the extension '\fI.tal\fR' are
utilized by fort as TAL.
.P
The TAL ("Trust Anchor Locator") is a text file that lists a few URLs which can
be used to access the "Trust Anchor" (the root of a particular RPKI tree) and
its public key. (See RFC 7730.)
.RE
.P

.BR \-r ", " \-\-local-repository=\fIDIRECTORY\fR
.RS 4
Path to a directory where the local cache of the repository will be stored
and/or read.
.P
Right now, FORT accesses RPKI repositories by way of \fIrsync\fR. During each
validation cycle, FORT will literally invoke an rsync command (see
\fBrsync.program\fR and \fBrsync.arguments-recursive\fR), which will download
the files into \fB--local-repository\fR. FORT’s validation operates on the
resulting copy.
.P
Because rsync uses delta encoding, you’re advised to keep this cache around. It
significantly speeds up subsequent validation cycles.
.P
By default, the path is \fI/tmp/fort/repository\fR.
.RE
.P

.B \-\-sync-strategy=(\fIoff\fR|\fIstrict\fR|\fIroot\fR|\fIroot-except-ta\fR)
.RS 4
\fIrsync\fR download strategy; states the way rsync URLs are approached during
downloads. It can have one of four values:
.IR off ", "
.IR strict ", "
.IB "root" "(default value)" \fR, \fR
.IR root-except-ta "."
.P
.I off
.RS 4
Skip all RSYNCs. (Validate the existing cache repository pointed by
--local-repository.)
.RE
.P
.I strict
.RS 4
In order to enable this strategy, FORT must be compiled using the flag:
ENABLE\_STRICT\_STRATEGY. e.g.
\fB $ make FORT_FLAGS='-DENABLE_STRICT_STRATEGY'\fR
.P
RSYNC every repository publication point separately. Only skip publication
points that have already been downloaded during the current validation cycle.
(Assuming each synchronization is recursive.)
.P
For example, suppose the validator gets certificates whose caRepository access
methods (in their Subject Information Access extensions) point to the following
publication points:
.P
1. rsync://rpki.example.com/foo/bar/
.br
2. rsync://rpki.example.com/foo/qux/
.br
3. rsync://rpki.example.com/foo/bar/
.br
4. rsync://rpki.example.com/foo/corge/grault/
.br
5. rsync://rpki.example.com/foo/corge/
.br
6. rsync://rpki.example.com/foo/corge/waldo/
.P
A validator following the `strict` strategy would download `bar`, download
`qux`, skip `bar`, download `corge/grault`, download `corge` and skip
`corge/waldo`.
.P
This is the slowest, but also the strictly correct sync strategy.
.RE
.P
.I root
.RS 4
For each publication point found, guess the root of its repository and RSYNC
that instead. Then skip any subsequent children of said root.
.P
(To guess the root of a repository, the validator counts four slashes, and
prunes the rest of the URL.)
.P
Reusing the caRepository URLs from the `strict` strategy (above) as example, a
validator following the `root` strategy would download
`rsync://rpki.example.com/foo`, and then skip everything else.
.P
Assuming that the repository is specifically structured to be found within as
few roots as possible, and they contain minimal RPKI-unrelated noise files, this
is the fastest synchronization strategy. At time of writing, this is true for
all the current official repositories.
.RE
.P
.I root-except-ta
.RS 4
Synchronizes the root certificate (the one pointed by the TAL) in 'strict' mode,
and once it's validated, synchronizes the rest of the repository in 'root' mode.
.P
Useful if you want 'root', but the root certificate is separated from the rest
of the repository. Also useful if you don't want the validator to download the
entire repository without first confirming the integrity and legitimacy of the
root certificate.
.RE
.RE
.P

.B \-\-shuffle-uris
.RS 4
If enabled, FORT will access TAL URLs in random order. This is meant for load
balancing. If disabled, FORT will access TAL URLs in sequential order.
.P
By default, the flag is disabled.
.P
This flag is only relevant if the TAL lists more than one URL. Regardless of
this flag, FORT will stop iterating through the URLs as soon as it finds one
that yields a successful traversal.
.RE
.P

.B \-\-maximum-certificate-depth=\fIUNSIGNED_INTEGER\fR
.RS 4
Maximum allowable certificate chain length. Meant to protect FORT from
iterating infinitely due to certificate chain loops.
.P
By default, it has a value of \fI32\fR. The minimum allowed value is 5.
.P
(Required to prevent loops and "other degenerate forms of the logical RPKI
hierarchy." (RFC 6481))
.RE
.P

.B \-\-slurm=(\fIFILE\fR|\fIDIRECTORY\fR)
.RS 4
Path to the SLURM FILE or SLURMs DIRECTORY.
.P
In case a DIRECTORY is set, the files with extension '\fI.slurm\fR' will be the
ones considered as SLURM files and FORT will use them.
.P
The SLURM definition is from RFC 8416. SLURM stands for "Simplified Local
Internet Number Resource Management with the RPKI", basically is a document
that can override (either as a filter or adding assertions) the global RPKI
repository data fetched by FORT; potentially useful for network operators.
.P
A basic example of a SLURM file can be seen in this manual at the
\fBEXAMPLES\fR section (it's almost the same as the one in RFC 8416).
.P
See more about SLURM configuration at FORT's web docs.
.RE
.P

.B \-\-mode=(\fIserver\fR|\fIstandalone\fR)
.RS 4
Commands the way FORT executes the validation, its possible values are:
.P
.I server
.RS 4
Enable the RTR server using the \fIserver.*\fR arguments.
.RE
.P
.I standalone
.RS 4
Disable the RTR server, the configuration options \fIserver.*\fR are ignored
and FORT performs an in-place standalone validation.
.RE
.P
By default, the mode is \fIserver\fR.
.RE
.P

.B \-\-server.address=\fINODE\fR
.RS 4
Hostname or numeric host address the RTR server will be bound to. Must resolve
to (or be) a bindable IP address. IPv4 and IPv6 are supported.
.P
If this field is omitted, FORT will attempt to bind the server using the IP
address \fIINADDR_ANY\fR (for an IPv4 address) or \fIIN6ADDR_ANY_INIT\fR (for
an IPv6 address). See \fBgetaddrinfo(3)\fR.
.RE
.P

.B \-\-server.port=\fISERVICE\fR
.RS 4
TCP port or service the server will be bound to.
.P
This is a string because a service alias can be used as a valid value. The
alias are commonly located at \fI/etc/services\fR. See also
\fBgetaddrinfo(3)\fR and \fBservices(5)\fR.
.P
The default port (323) is privileged. To improve security, either change or
jail it.
.RE
.P

.B \-\-server.backlog=\fIUNSIGNED_INTEGER\fR
.RS 4
RTR server’s listen queue length. It’s the second argument of the function
\fIlisten\fR (see more at man \fBlisten(2)\fR). This provides a hint to the
implementation which the implementation shall use to limit the number of
outstanding connections in the socket’s listen queue.
.P
By default, it has a value of \fISOMAXCONN\fR.
.RE
.P

.B \-\-server.interval.validation=\fIUNSIGNED_INTEGER\fR
.RS 4
Number of seconds that FORT will sleep between validation cycles. The timer
starts counting every time a validation is finished, not every time it begins.
Therefore, the actual validation loop is longer than this number.
.P
By default, it has a value of \fI3600\fR.
.RE
.P

.B \-\-server.interval.refresh=\fIUNSIGNED_INTEGER\fR
.RS 4
Number of seconds that a router should wait before the next attempt to poll 
FORT using either a Serial Query PDU or Reset Query PDU. Countdown for this
timer starts upon receipt of an End Of Data PDU (this should be administered by
the client).
.P
This value is utilized only on RTR version 1 sessions (more information at RFC
8210 section 6).
.P
By default, it has a value of \fI3600\fR. Minimum allowed value: \fI1\fR,
maximum allowed value \fI86400\fR.
.RE
.P

.B \-\-server.interval.retry=\fIUNSIGNED_INTEGER\fR
.RS 4
Number of seconds that a router should wait before retrying a failed Serial
Query PDU or Reset Query PDU. Countdown for this timer starts upon failure of
the query and restarts after each subsequent failure until a query succeeds
(this should be administered by the client).
.P
This value is utilized only on RTR version 1 sessions (more information at RFC
8210 section 6).
.P
By default, it has a value of \fI600\fR. Minimum allowed value: \fI1\fR,
maximum allowed value \fI7200\fR.
.RE
.P

.B \-\-server.interval.expire=\fIUNSIGNED_INTEGER\fR
.RS 4
Number of seconds that a router can retain the current version of data while
unable to perform a successful subsequent query. Countdown for this timer starts
upon receipt of an End Of Data PDU (this should be administered by the client).
.P
This value is utilized only on RTR version 1 sessions (more information at RFC
8210 section 6).
.P
By default, it has a value of \fI7200\fR. Minimum allowed value: \fI600\fR,
maximum allowed value \fI172800\fR. It must be larger than
\fIserver.interval.refresh\fR and \fIserver.interval.retry\fR.
.RE
.P

.BR \-\-log.level=(\fIerror\fR|\fIwarning\fR|\fIinfo\fR|\fIdebug\fR)
.RS 4
Defines which messages will be logged according to its priority, e.g. a value
of \fIinfo\fR will log messages of equal or higher level (\fIinfo\fR,
\fIwarning\fR, and \fIerror\fR).
.P
The priority levels, from higher to lowest, are:
.RS 4
.br
- \fIerror\fR
.br
- \fIwarning\fR
.br
- \fIinfo\fR
.br
- \fIdebug\fR
.RE
.P
By default, it has a value of \fIwarning\fR.
.RE
.P

.BR \-\-log.output=(\fIsyslog\fR|\fIconsole\fR)
.RS 4
Desired output where the logs will be printed.
.P
The value \fIconsole\fR will log messages at standard output and standard error;
\fIsyslog\fR will log to syslog.
.P
Depending on the OS, distinct implementations of syslog could be installed
(syslog, rsyslog, or syslog-ng are the most common ones). Syslog usage and
configuration is out of this man scope.
.P
By default, it has a value of \fIconsole\fR.
.P
More information about Logging can be consulted at FORT's web docs.
.RE
.P

.BR \-c ", " \-\-log.color-output
.RS 4
If enabled, the logging output will contain ANSI color codes. Meant for human
consumption.
.P
Meaningful only if \fI--log.output\fR value is \fIconsole\fR.
.RE
.P

.B \-\-log.file-name-format=(\fIglobal-url\fR|\fIlocal-path\fR|\fIfile-name\fR)
.RS 4
Decides which version of file names should be printed during most debug/error
messages.
.P
Suppose a certificate was downloaded from
`rsync://rpki.example.com/foo/bar/baz.cer` into the local cache `repository/`:
.P
.I global-url
.RS 4
Will print the certificate's name as `rsync://rpki.example.com/foo/bar/baz.cer`.
.RE
.P
.I local-path
.RS 4
Will print the certificate's name as
`repository/rpki.example.com/foo/bar/baz.cer`.
.RE
.P
.I file-name
.RS 4
Will print the certificate's name as `baz.cer`.
.RE
.P
.RE

.B \-\-output.roa=\fIFILE\fR
.RS 4
File where the ROAs will be printed in CSV format.
.P
When the \fIFILE\fR is specified, its content will be overwritten by the
resulting ROAs of the validation (if FILE doesn't exists, it'll be created).
.P
Each line of the result is printed in the following order: AS, Prefix, Max
prefix length; the first line contains those column descriptors.
.P
In order to print the ROAs at console, use a hyphen as the \fIFILE\fR value, eg.
.B \-\-output.roa=-
.RE

.B \-\-output.bgpsec=\fIFILE\fR
.RS 4
File where the BGPsec Router Keys will be printed in CSV format. Since most of
the data is binary (Subject Key Identifier and Subject Public Key Info), such
data is base64url encoded without trailing pads.
.P
When the \fIFILE\fR is specified, its content will be overwritten by the
resulting Router Keys of the validation (if FILE doesn't exists, it'll be
created).
.P
Each line of the result is printed in the following order: AS, Subject Key
Identifier, Subject Public Key Info; the first line contains those column
descriptors.
.P
In order to print the Router Keys at console, use a hyphen as the \fIFILE\fR
value, eg.
.B \-\-output.bgpsec=-
.RE

.SH EXAMPLES
.B fort \-t /tmp/tal \-r /tmp/repository \-\-server.port 9323
.RS 4
Run FORT with all the default values, using a custom TALs directory, a
custom repository directory as well, and binding the RTR server to port 9323.
.RE
.P

.B fort \-t /tmp/tal \-r /tmp/repository \-\-mode=standalone \-\-output.roa -
.RS 4
Run FORT as standalone and output ROAs CSV to the console.
.RE
.P

.nf
\fBfort \-t /tmp/tal \-r /tmp/repository \\
     \-\-mode=standalone \\
     \-\-slurm /tmp/myslurm.slurm\fR
.fi
.RS 4
Run FORT as standalone and using a SLURM file.
.RE
.P

.B fort --configuration-file conf.json
.RS 4
Run FORT using the JSON configuration file \fIconf.json\fR.
.RE
.P

.nf
\fBfort \-t /tmp/tal \-r /tmp/repository \\
     \-\-server.address ::1 \-\-server.port 9323 \\
     \-\-server.interval.validation 1800 \\
     \-\-output.roa /tmp/roas.csv\fR
.fi
.RS 4
Run FORT with RTR server listening on IPv6 address \fI::1\fR, port 9323,
validating every 30 minutes, and printing the ROAs CSV in a file.
.RE
.P

.B Complete configuration file
.RS 4
This is an example of a valid JSON configuration file with all its members set
to a specific value:
.nf

{
  "tal": "/tmp/fort/tal/",
  "local-repository": "/tmp/fort/repository/",
  "sync-strategy": "root",
  "shuffle-uris": true,
  "maximum-certificate-depth": 32,
  "mode": "server",
  "slurm": "/tmp/fort/test.slurm",
  "server": {
    "address": "127.0.0.1",
    "port": "8323",
    "backlog": 64,
    "interval": {
      "validation": 3600,
      "refresh": 3600,
      "retry": 600,
      "expire": 7200
    }
  },
  "log": {
    "level": "warning",
    "output": "console",
    "color-output": true,
    "file-name-format": "local-path"
  },
  "rsync": {
    "program": "rsync",
    "arguments-recursive": [
      "--recursive",
      "--delete",
      "--times",
      "--contimeout=20",
      "$REMOTE",
      "$LOCAL"
    ],
    "arguments-flat": [
      "--times",
      "--contimeout=20",
      "--dirs",
      "$REMOTE",
      "$LOCAL"
    ]
  },
  "incidences": [
    {
      "name": "incid-hashalg-has-params",
      "action": "ignore"
    }
  ],
  "output": {
    "roa": "/tmp/fort/roas.csv",
    "bgpsec": "/tmp/fort/bgpsec.csv"
  }
}
.fi
.RE
.P

.B Dummy SLURM file
.RS 4
This is an example of a SLURM file with some prefix filters and assertions, as
well as some dummy Router Keys (BGPsec) info:
.nf

{
  "slurmVersion": 1,
  "validationOutputFilters": {
    "prefixFilters": [
      {
        "prefix": "192.0.2.0/24",
        "comment": "All VRPs encompassed by prefix"
      },
      {
        "asn": 64496,
        "comment": "All VRPs matching ASN"
      },
      {
        "prefix": "198.51.100.0/24",
        "asn": 64497,
        "comment": "All VRPs encompassed by prefix, matching ASN"
      }
    ],
    "bgpsecFilters": [
      {
        "asn": 64496,
        "comment": "All keys for ASN"
      },
      {
        "SKI": "Q8KMeBsCto1PJ6EuhowleIGNL7A",
        "comment": "Key matching Router SKI"
      },
      {
        "asn": 64497,
        "SKI": "g5RQYCnkMpDqEbt9WazTeB19nZs",
        "comment": "Key for ASN 64497 matching Router SKI"
      }
    ]
  },
  "locallyAddedAssertions": {
    "prefixAssertions": [
      {
        "asn": 64496,
        "prefix": "198.51.100.0/24",
        "comment": "My other important route"
      },
      {
        "asn": 64496,
        "prefix": "2001:DB8::/32",
        "maxPrefixLength": 48,
        "comment": "My other important de-aggregated routes"
      }
    ],
    "bgpsecAssertions": [
      {
        "asn": 64496,
        "SKI": "Dulqji-sUM5sX5M-3mqngKaFDjE",
        "routerPublicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE-rkSLXlPpL_m-L\
7CfCfKrv1FHrM55FsIc8fMlnjHE6Y5nTuCn3UgWfCV6sYuGUZzPZ0Ey6AvezmfcELUB87eBA"
      }
    ]
  }
}
.fi
.RE
.P

.\".SH COPYRIGHT
.\" FORT-validator 2019
.\" Licensed under the blah blah...

.SH SEE ALSO
.B Regular man pages
.RS 4
.IR getaddrinfo(3) ", " services(5) ", " listen(2) ", " rsync(1)
.RE
.P

.B FORTs official documentation
.RS 4
More documentation about FORT validator can be consulted at github repository
(https://github.com/NICMx/FORT-validator) and github website
(https://nicmx.github.io/FORT-validator/)
.RE
