/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef VALIDATOR_ASN1_ASN1C_CONTENTINFO_H_
#define VALIDATOR_ASN1_ASN1C_CONTENTINFO_H_

#include "validator/asn1/asn1c/ANY.h"
#include "validator/asn1/asn1c/ContentType.h"

/* ContentInfo */
typedef struct ContentInfo {
	ContentType_t	 contentType;
	ANY_t	 content;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ContentInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentInfo;

#endif /* VALIDATOR_ASN1_ASN1C_CONTENTINFO_H_ */
