ASN_MODULE_SRCS=	\
	validator/asn1/asn1c/IPAddrBlocks.c	\
	validator/asn1/asn1c/IPAddressFamily.c	\
	validator/asn1/asn1c/IPAddressChoice.c	\
	validator/asn1/asn1c/IPAddressOrRange.c	\
	validator/asn1/asn1c/IPAddressRange.c	\
	validator/asn1/asn1c/IPAddress.c	\
	validator/asn1/asn1c/ASIdentifiers.c	\
	validator/asn1/asn1c/ASIdentifierChoice.c	\
	validator/asn1/asn1c/ASIdOrRange.c	\
	validator/asn1/asn1c/ASProviderAttestation.c	\
	validator/asn1/asn1c/ProviderASSet.c	\
	validator/asn1/asn1c/ASRange.c	\
	validator/asn1/asn1c/ASId.c	\
	validator/asn1/asn1c/AttributeType.c	\
	validator/asn1/asn1c/AttributeValue.c	\
	validator/asn1/asn1c/AttributeTypeAndValue.c	\
	validator/asn1/asn1c/Name.c	\
	validator/asn1/asn1c/RDNSequence.c	\
	validator/asn1/asn1c/DistinguishedName.c	\
	validator/asn1/asn1c/RelativeDistinguishedName.c	\
	validator/asn1/asn1c/Version.c	\
	validator/asn1/asn1c/CertificateSerialNumber.c	\
	validator/asn1/asn1c/Time.c	\
	validator/asn1/asn1c/Extensions.c	\
	validator/asn1/asn1c/Extension.c	\
	validator/asn1/asn1c/CertificateList.c	\
	validator/asn1/asn1c/TBSCertList.c	\
	validator/asn1/asn1c/AlgorithmIdentifier.c	\
	validator/asn1/asn1c/ContentInfo.c	\
	validator/asn1/asn1c/ContentType.c	\
	validator/asn1/asn1c/SignedData.c	\
	validator/asn1/asn1c/DigestAlgorithmIdentifiers.c	\
	validator/asn1/asn1c/SignerInfos.c	\
	validator/asn1/asn1c/EncapsulatedContentInfo.c	\
	validator/asn1/asn1c/SignedDataPKCS7.c	\
	validator/asn1/asn1c/EncapsulatedContentInfoPKCS7.c	\
	validator/asn1/asn1c/ContentTypePKCS7.c	\
	validator/asn1/asn1c/SignerInfo.c	\
	validator/asn1/asn1c/SignerIdentifier.c	\
	validator/asn1/asn1c/SignedAttributes.c	\
	validator/asn1/asn1c/UnsignedAttributes.c	\
	validator/asn1/asn1c/CMSAttribute.c	\
	validator/asn1/asn1c/CMSAttributeValue.c	\
	validator/asn1/asn1c/SignatureValue.c	\
	validator/asn1/asn1c/CMSSubjectKeyIdentifier.c	\
	validator/asn1/asn1c/DigestAlgorithmIdentifier.c	\
	validator/asn1/asn1c/SignatureAlgorithmIdentifier.c	\
	validator/asn1/asn1c/RevocationInfoChoices.c	\
	validator/asn1/asn1c/RevocationInfoChoice.c	\
	validator/asn1/asn1c/OtherRevocationInfoFormat.c	\
	validator/asn1/asn1c/Certificate.c	\
	validator/asn1/asn1c/CertificateSet.c	\
	validator/asn1/asn1c/CRL.c	\
	validator/asn1/asn1c/IssuerAndSerialNumber.c	\
	validator/asn1/asn1c/CMSVersion.c	\
	validator/asn1/asn1c/MessageDigest.c	\
	validator/asn1/asn1c/SigningTime.c	\
	validator/asn1/asn1c/Countersignature.c	\
	validator/asn1/asn1c/RouteOriginAttestation.c	\
	validator/asn1/asn1c/ROAIPAddressFamily.c	\
	validator/asn1/asn1c/ROAIPAddress.c	\
	validator/asn1/asn1c/RsyncRequest.c	\
	validator/asn1/asn1c/Manifest.c	\
	validator/asn1/asn1c/FileAndHash.c	\
	validator/asn1/asn1c/BinarySigningTime.c	\
	validator/asn1/asn1c/BinaryTime.c

ASN_MODULE_HDRS=	\
	validator/asn1/asn1c/IPAddrBlocks.h	\
	validator/asn1/asn1c/IPAddressFamily.h	\
	validator/asn1/asn1c/IPAddressChoice.h	\
	validator/asn1/asn1c/IPAddressOrRange.h	\
	validator/asn1/asn1c/IPAddressRange.h	\
	validator/asn1/asn1c/IPAddress.h	\
	validator/asn1/asn1c/ASIdentifiers.h	\
	validator/asn1/asn1c/ASIdentifierChoice.h	\
	validator/asn1/asn1c/ASIdOrRange.h	\
	validator/asn1/asn1c/ASProviderAttestation.h	\
	validator/asn1/asn1c/ProviderASSet.h	\
	validator/asn1/asn1c/ASRange.h	\
	validator/asn1/asn1c/ASId.h	\
	validator/asn1/asn1c/AttributeType.h	\
	validator/asn1/asn1c/AttributeValue.h	\
	validator/asn1/asn1c/AttributeTypeAndValue.h	\
	validator/asn1/asn1c/Name.h	\
	validator/asn1/asn1c/RDNSequence.h	\
	validator/asn1/asn1c/DistinguishedName.h	\
	validator/asn1/asn1c/RelativeDistinguishedName.h	\
	validator/asn1/asn1c/Version.h	\
	validator/asn1/asn1c/CertificateSerialNumber.h	\
	validator/asn1/asn1c/Time.h	\
	validator/asn1/asn1c/Extensions.h	\
	validator/asn1/asn1c/Extension.h	\
	validator/asn1/asn1c/CertificateList.h	\
	validator/asn1/asn1c/TBSCertList.h	\
	validator/asn1/asn1c/AlgorithmIdentifier.h	\
	validator/asn1/asn1c/ContentInfo.h	\
	validator/asn1/asn1c/ContentType.h	\
	validator/asn1/asn1c/SignedData.h	\
	validator/asn1/asn1c/DigestAlgorithmIdentifiers.h	\
	validator/asn1/asn1c/SignerInfos.h	\
	validator/asn1/asn1c/EncapsulatedContentInfo.h	\
	validator/asn1/asn1c/SignedDataPKCS7.h	\
	validator/asn1/asn1c/EncapsulatedContentInfoPKCS7.h	\
	validator/asn1/asn1c/ContentTypePKCS7.h	\
	validator/asn1/asn1c/SignerInfo.h	\
	validator/asn1/asn1c/SignerIdentifier.h	\
	validator/asn1/asn1c/SignedAttributes.h	\
	validator/asn1/asn1c/UnsignedAttributes.h	\
	validator/asn1/asn1c/CMSAttribute.h	\
	validator/asn1/asn1c/CMSAttributeValue.h	\
	validator/asn1/asn1c/SignatureValue.h	\
	validator/asn1/asn1c/CMSSubjectKeyIdentifier.h	\
	validator/asn1/asn1c/DigestAlgorithmIdentifier.h	\
	validator/asn1/asn1c/SignatureAlgorithmIdentifier.h	\
	validator/asn1/asn1c/RevocationInfoChoices.h	\
	validator/asn1/asn1c/RevocationInfoChoice.h	\
	validator/asn1/asn1c/OtherRevocationInfoFormat.h	\
	validator/asn1/asn1c/Certificate.h	\
	validator/asn1/asn1c/CertificateSet.h	\
	validator/asn1/asn1c/CRL.h	\
	validator/asn1/asn1c/IssuerAndSerialNumber.h	\
	validator/asn1/asn1c/CMSVersion.h	\
	validator/asn1/asn1c/MessageDigest.h	\
	validator/asn1/asn1c/SigningTime.h	\
	validator/asn1/asn1c/Countersignature.h	\
	validator/asn1/asn1c/RouteOriginAttestation.h	\
	validator/asn1/asn1c/ROAIPAddressFamily.h	\
	validator/asn1/asn1c/ROAIPAddress.h	\
	validator/asn1/asn1c/RsyncRequest.h	\
	validator/asn1/asn1c/Manifest.h	\
	validator/asn1/asn1c/FileAndHash.h	\
	validator/asn1/asn1c/BinarySigningTime.h	\
	validator/asn1/asn1c/BinaryTime.h

ASN_MODULE_HDRS+=validator/asn1/asn1c/ANY.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/ANY.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/OCTET_STRING.h
ASN_MODULE_HDRS+=validator/asn1/asn1c/OPEN_TYPE.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/OPEN_TYPE.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/constr_CHOICE.h
ASN_MODULE_HDRS+=validator/asn1/asn1c/BOOLEAN.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/BOOLEAN.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/GeneralizedTime.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/GeneralizedTime.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/IA5String.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/IA5String.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/INTEGER.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/INTEGER.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/NULL.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/NULL.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/OBJECT_IDENTIFIER.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/OBJECT_IDENTIFIER.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/UTCTime.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/UTCTime.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/asn_SEQUENCE_OF.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/asn_SEQUENCE_OF.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/asn_SET_OF.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/asn_SET_OF.c
ASN_MODULE_SRCS+=validator/asn1/asn1c/constr_CHOICE.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/constr_SEQUENCE.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/constr_SEQUENCE.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/constr_SEQUENCE_OF.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/constr_SEQUENCE_OF.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/constr_SET_OF.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/constr_SET_OF.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/asn_ioc.h
ASN_MODULE_HDRS+=validator/asn1/asn1c/asn_system.h
ASN_MODULE_HDRS+=validator/asn1/asn1c/asn_codecs.h
ASN_MODULE_HDRS+=validator/asn1/asn1c/asn_internal.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/asn_internal.c
ASN_MODULE_SRCS+=validator/asn1/asn1c/OCTET_STRING.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/BIT_STRING.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/BIT_STRING.c
ASN_MODULE_SRCS+=validator/asn1/asn1c/asn_codecs_prim.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/asn_codecs_prim.h
ASN_MODULE_HDRS+=validator/asn1/asn1c/ber_tlv_length.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/ber_tlv_length.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/ber_tlv_tag.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/ber_tlv_tag.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/ber_decoder.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/ber_decoder.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/der_encoder.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/der_encoder.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/constr_TYPE.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/constr_TYPE.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/constraints.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/constraints.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/json_encoder.c
ASN_MODULE_HDRS+=validator/asn1/asn1c/json_encoder.h
ASN_MODULE_HDRS+=validator/asn1/asn1c/xer_encoder.h
ASN_MODULE_SRCS+=validator/asn1/asn1c/xer_encoder.c
