/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc5280-a.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef VALIDATOR_ASN1_ASN1C_RDNSEQUENCE_H_
#define VALIDATOR_ASN1_ASN1C_RDNSEQUENCE_H_

#include "validator/asn1/asn1c/RelativeDistinguishedName.h"
#include "validator/asn1/asn1c/asn_SEQUENCE_OF.h"

/* RDNSequence */
typedef struct RDNSequence {
	A_SEQUENCE_OF(struct RelativeDistinguishedName) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RDNSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RDNSequence;
extern asn_SET_OF_specifics_t asn_SPC_RDNSequence_specs_1;
extern asn_TYPE_member_t asn_MBR_RDNSequence_1[1];

#endif /* VALIDATOR_ASN1_ASN1C_RDNSEQUENCE_H_ */
