/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "AsList.h"

static asn_oer_constraints_t asn_OER_type_AsList_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
asn_TYPE_member_t asn_MBR_AsList_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ASIdOrRange,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_AsList_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_AsList_specs_1 = {
	sizeof(struct AsList),
	offsetof(struct AsList, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_AsList = {
	"AsList",
	"AsList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_AsList_tags_1,
	sizeof(asn_DEF_AsList_tags_1)
		/sizeof(asn_DEF_AsList_tags_1[0]), /* 1 */
	asn_DEF_AsList_tags_1,	/* Same as above */
	sizeof(asn_DEF_AsList_tags_1)
		/sizeof(asn_DEF_AsList_tags_1[0]), /* 1 */
	{ &asn_OER_type_AsList_constr_1, 0, SEQUENCE_OF_constraint },
	asn_MBR_AsList_1,
	1,	/* Single element */
	&asn_SPC_AsList_specs_1	/* Additional specs */
};

