/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RPKI-ASPA-2023"
 * 	found in "aspa.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_ASProviderAttestation_H_
#define	_ASProviderAttestation_H_

/* Including external dependencies */
#include "asn1/asn1c/INTEGER.h"
#include "asn1/asn1c/ASId.h"
#include "asn1/asn1c/ProviderASSet.h"
#include "asn1/asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ASProviderAttestation */
typedef struct ASProviderAttestation {
	INTEGER_t	*version	/* DEFAULT 0 */;
	ASId_t	 customerASID;
	ProviderASSet_t	 providers;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASProviderAttestation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASProviderAttestation;

#ifdef __cplusplus
}
#endif

#endif	/* _ASProviderAttestation_H_ */
#include "asn1/asn1c/asn_internal.h"
