/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RPKI-ASPA-2023"
 * 	found in "aspa.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "asn1/asn1c/ASProviderAttestation.h"

static int asn_DFL_2_cmp_0(const void *sptr) {
	const INTEGER_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	long value;
	if(asn_INTEGER2long(st, &value))
		return -1;
	return (value != 0);
}
static int asn_DFL_2_set_0(void **sptr) {
	INTEGER_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	return asn_long2INTEGER(st, 0);
}
static asn_TYPE_member_t asn_MBR_ASProviderAttestation_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ASProviderAttestation, version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_2_set_0,	/* Set DEFAULT 0 */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASProviderAttestation, customerASID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ASId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"customerASID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASProviderAttestation, providers),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ProviderASSet,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"providers"
		},
};
static const ber_tlv_tag_t asn_DEF_ASProviderAttestation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASProviderAttestation_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* customerASID */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* providers */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* version */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASProviderAttestation_specs_1 = {
	sizeof(struct ASProviderAttestation),
	offsetof(struct ASProviderAttestation, _asn_ctx),
	asn_MAP_ASProviderAttestation_tag2el_1,
	3,	/* Count of tags in the map */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASProviderAttestation = {
	"ASProviderAttestation",
	"ASProviderAttestation",
	&asn_OP_SEQUENCE,
	asn_DEF_ASProviderAttestation_tags_1,
	sizeof(asn_DEF_ASProviderAttestation_tags_1)
		/sizeof(asn_DEF_ASProviderAttestation_tags_1[0]), /* 1 */
	asn_DEF_ASProviderAttestation_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASProviderAttestation_tags_1)
		/sizeof(asn_DEF_ASProviderAttestation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASProviderAttestation_1,
	3,	/* Elements count */
	&asn_SPC_ASProviderAttestation_specs_1	/* Additional specs */
};

