/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IPAddrAndASCertExtn"
 * 	found in "rfc3779.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "asn1/asn1c/ASRange.h"

asn_TYPE_member_t asn_MBR_ASRange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASRange, min),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ASId,
		NULL,
		{ NULL, NULL, NULL },
		NULL, NULL, /* No default value */
		"min"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASRange, max),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ASId,
		NULL,
		{ NULL, NULL, NULL },
		NULL, NULL, /* No default value */
		"max"
		},
};
static const ber_tlv_tag_t asn_DEF_ASRange_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASRange_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* min */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* max */
};
asn_SEQUENCE_specifics_t asn_SPC_ASRange_specs_1 = {
	sizeof(struct ASRange),
	offsetof(struct ASRange, _asn_ctx),
	asn_MAP_ASRange_tag2el_1,
	2,	/* Count of tags in the map */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASRange = {
	"ASRange",
	"ASRange",
	&asn_OP_SEQUENCE,
	asn_DEF_ASRange_tags_1,
	sizeof(asn_DEF_ASRange_tags_1)
		/sizeof(asn_DEF_ASRange_tags_1[0]), /* 1 */
	asn_DEF_ASRange_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASRange_tags_1)
		/sizeof(asn_DEF_ASRange_tags_1[0]), /* 1 */
	{ NULL, NULL, SEQUENCE_constraint },
	asn_MBR_ASRange_1,
	2,	/* Elements count */
	&asn_SPC_ASRange_specs_1	/* Additional specs */
};
