/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc5280-a.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_AttributeValue_H_
#define	_AttributeValue_H_

#include "asn1/asn1c/ANY.h"

/* AttributeValue */
typedef ANY_t	 AttributeValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeValue;
asn_struct_free_f AttributeValue_free;
asn_struct_print_f AttributeValue_print;
asn_constr_check_f AttributeValue_constraint;
ber_type_decoder_f AttributeValue_decode_ber;
der_type_encoder_f AttributeValue_encode_der;
xer_type_encoder_f AttributeValue_encode_xer;

#endif	/* _AttributeValue_H_ */
