/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_CMSAttributeValue_H_
#define	_CMSAttributeValue_H_

#include "asn1/asn1c/ANY.h"
#include "asn1/asn1c/constr_TYPE.h"

/* CMSAttributeValue */
typedef ANY_t	 CMSAttributeValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMSAttributeValue;
asn_struct_free_f CMSAttributeValue_free;
asn_struct_print_f CMSAttributeValue_print;
asn_constr_check_f CMSAttributeValue_constraint;
ber_type_decoder_f CMSAttributeValue_decode_ber;
der_type_encoder_f CMSAttributeValue_encode_der;
xer_type_encoder_f CMSAttributeValue_encode_xer;

#endif	/* _CMSAttributeValue_H_ */
