/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_CMSAttribute_H_
#define	_CMSAttribute_H_


#include "asn1/asn1c/asn_application.h"

/* Including external dependencies */
#include "asn1/asn1c/OBJECT_IDENTIFIER.h"
#include "asn1/asn1c/CMSAttributeValue.h"
#include "asn1/asn1c/asn_SET_OF.h"
#include "asn1/asn1c/constr_SET_OF.h"
#include "asn1/asn1c/constr_SEQUENCE.h"

/* CMSAttribute */
typedef struct CMSAttribute {
	OBJECT_IDENTIFIER_t	 attrType;
	struct CMSAttribute__attrValues {
		A_SET_OF(CMSAttributeValue_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} attrValues;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CMSAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMSAttribute;
extern asn_SEQUENCE_specifics_t asn_SPC_CMSAttribute_specs_1;
extern asn_TYPE_member_t asn_MBR_CMSAttribute_1[2];

#endif	/* _CMSAttribute_H_ */
#include "asn1/asn1c/asn_internal.h"
