/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc5280-a.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "asn1/asn1c/DistinguishedName.h"

/*
 * This type is implemented using RDNSequence,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_DistinguishedName_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_DistinguishedName = {
	"DistinguishedName",
	"DistinguishedName",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_DistinguishedName_tags_1,
	sizeof(asn_DEF_DistinguishedName_tags_1)
		/sizeof(asn_DEF_DistinguishedName_tags_1[0]), /* 1 */
	asn_DEF_DistinguishedName_tags_1,	/* Same as above */
	sizeof(asn_DEF_DistinguishedName_tags_1)
		/sizeof(asn_DEF_DistinguishedName_tags_1[0]), /* 1 */
	{ NULL, NULL, SEQUENCE_OF_constraint },
	asn_MBR_RDNSequence_1,
	1,	/* Single element */
	&asn_SPC_RDNSequence_specs_1	/* Additional specs */
};
