/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_EncapsulatedContentInfo_H_
#define	_EncapsulatedContentInfo_H_

#include "asn1/asn1c/ContentType.h"
#include "asn1/asn1c/OCTET_STRING.h"
#include "asn1/asn1c/constr_SEQUENCE.h"
#include "asn1/asn1c/constr_TYPE.h"

/* EncapsulatedContentInfo */
typedef struct EncapsulatedContentInfo {
	ContentType_t	 eContentType;
	OCTET_STRING_t	*eContent	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncapsulatedContentInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncapsulatedContentInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_EncapsulatedContentInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_EncapsulatedContentInfo_1[2];

#endif	/* _EncapsulatedContentInfo_H_ */
