/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_FileNameAndHash_H_
#define	_FileNameAndHash_H_


#include "asn1/asn1c/asn_application.h"

/* Including external dependencies */
#include "asn1/asn1c/IA5String.h"
#include "asn1/asn1c/OCTET_STRING.h"
#include "asn1/asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FileNameAndHash */
typedef struct FileNameAndHash {
	IA5String_t	*fileName	/* OPTIONAL */;
	OCTET_STRING_t	 hash;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileNameAndHash_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileNameAndHash;
extern asn_SEQUENCE_specifics_t asn_SPC_FileNameAndHash_specs_1;
extern asn_TYPE_member_t asn_MBR_FileNameAndHash_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _FileNameAndHash_H_ */
#include "asn1/asn1c/asn_internal.h"
