/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "FileNameAndHash.h"

asn_TYPE_member_t asn_MBR_FileNameAndHash_1[] = {
	{ ATF_POINTER, 1, offsetof(struct FileNameAndHash, fileName),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fileName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FileNameAndHash, hash),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hash"
		},
};
static const int asn_MAP_FileNameAndHash_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_FileNameAndHash_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FileNameAndHash_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* hash */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* fileName */
};
asn_SEQUENCE_specifics_t asn_SPC_FileNameAndHash_specs_1 = {
	sizeof(struct FileNameAndHash),
	offsetof(struct FileNameAndHash, _asn_ctx),
	asn_MAP_FileNameAndHash_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_FileNameAndHash_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FileNameAndHash = {
	"FileNameAndHash",
	"FileNameAndHash",
	&asn_OP_SEQUENCE,
	asn_DEF_FileNameAndHash_tags_1,
	sizeof(asn_DEF_FileNameAndHash_tags_1)
		/sizeof(asn_DEF_FileNameAndHash_tags_1[0]), /* 1 */
	asn_DEF_FileNameAndHash_tags_1,	/* Same as above */
	sizeof(asn_DEF_FileNameAndHash_tags_1)
		/sizeof(asn_DEF_FileNameAndHash_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_FileNameAndHash_1,
	2,	/* Elements count */
	&asn_SPC_FileNameAndHash_specs_1	/* Additional specs */
};

