/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_IPAddressFamilyItem_H_
#define	_IPAddressFamilyItem_H_


#include "asn1/asn1c/asn_application.h"

/* Including external dependencies */
#include "asn1/asn1c/OCTET_STRING.h"
#include "IPAddressOrRange.h"
#include "asn1/asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* IPAddressFamilyItem */
typedef struct IPAddressFamilyItem {
	OCTET_STRING_t	 addressFamily;
	IPAddressOrRange_t	 iPAddressOrRange;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPAddressFamilyItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPAddressFamilyItem;
extern asn_SEQUENCE_specifics_t asn_SPC_IPAddressFamilyItem_specs_1;
extern asn_TYPE_member_t asn_MBR_IPAddressFamilyItem_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _IPAddressFamilyItem_H_ */
#include "asn1/asn1c/asn_internal.h"
