/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "IPAddressFamilyItem.h"

static int
memb_addressFamily_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 2 && size <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_addressFamily_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(2..3)) */};
asn_TYPE_member_t asn_MBR_IPAddressFamilyItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddressFamilyItem, addressFamily),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_addressFamily_constr_2, 0,  memb_addressFamily_constraint_1 },
		0, 0, /* No default value */
		"addressFamily"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddressFamilyItem, iPAddressOrRange),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_IPAddressOrRange,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iPAddressOrRange"
		},
};
static const ber_tlv_tag_t asn_DEF_IPAddressFamilyItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IPAddressFamilyItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* addressPrefix */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* addressFamily */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* addressRange */
};
asn_SEQUENCE_specifics_t asn_SPC_IPAddressFamilyItem_specs_1 = {
	sizeof(struct IPAddressFamilyItem),
	offsetof(struct IPAddressFamilyItem, _asn_ctx),
	asn_MAP_IPAddressFamilyItem_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IPAddressFamilyItem = {
	"IPAddressFamilyItem",
	"IPAddressFamilyItem",
	&asn_OP_SEQUENCE,
	asn_DEF_IPAddressFamilyItem_tags_1,
	sizeof(asn_DEF_IPAddressFamilyItem_tags_1)
		/sizeof(asn_DEF_IPAddressFamilyItem_tags_1[0]), /* 1 */
	asn_DEF_IPAddressFamilyItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_IPAddressFamilyItem_tags_1)
		/sizeof(asn_DEF_IPAddressFamilyItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IPAddressFamilyItem_1,
	2,	/* Elements count */
	&asn_SPC_IPAddressFamilyItem_specs_1	/* Additional specs */
};

