/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_MessageDigest_H_
#define	_MessageDigest_H_

#include "asn1/asn1c/OCTET_STRING.h"

/* MessageDigest */
typedef OCTET_STRING_t	 MessageDigest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageDigest;
asn_struct_free_f MessageDigest_free;
asn_struct_print_f MessageDigest_print;
asn_constr_check_f MessageDigest_constraint;
ber_type_decoder_f MessageDigest_decode_ber;
der_type_encoder_f MessageDigest_encode_der;
xer_type_encoder_f MessageDigest_encode_xer;

#endif	/* _MessageDigest_H_ */
