/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_OtherRevocationInfoFormat_H_
#define	_OtherRevocationInfoFormat_H_


#include "asn1/asn1c/asn_application.h"

/* Including external dependencies */
#include "asn1/asn1c/OBJECT_IDENTIFIER.h"
#include "asn1/asn1c/ANY.h"
#include "asn1/asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OtherRevocationInfoFormat */
typedef struct OtherRevocationInfoFormat {
	OBJECT_IDENTIFIER_t	 otherRevInfoFormat;
	ANY_t	 otherRevInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherRevocationInfoFormat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherRevocationInfoFormat;
extern asn_SEQUENCE_specifics_t asn_SPC_OtherRevocationInfoFormat_specs_1;
extern asn_TYPE_member_t asn_MBR_OtherRevocationInfoFormat_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _OtherRevocationInfoFormat_H_ */
#include "asn1/asn1c/asn_internal.h"
