/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RPKI-ASPA-2023"
 * 	found in "aspa.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_ProviderASSet_H_
#define	_ProviderASSet_H_

/* Including external dependencies */
#include "asn1/asn1c/ASId.h"
#include "asn1/asn1c/asn_SEQUENCE_OF.h"
#include "asn1/asn1c/constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ProviderASSet */
typedef struct ProviderASSet {
	A_SEQUENCE_OF(ASId_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProviderASSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProviderASSet;
extern asn_SET_OF_specifics_t asn_SPC_ProviderASSet_specs_1;
extern asn_TYPE_member_t asn_MBR_ProviderASSet_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _ProviderASSet_H_ */
#include "asn1/asn1c/asn_internal.h"
