/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "ResourceBlock.h"

static asn_oer_constraints_t asn_OER_type_ResourceBlock_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_member_t asn_MBR_ResourceBlock_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ResourceBlock, asID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AsList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"asID"
		},
	{ ATF_POINTER, 1, offsetof(struct ResourceBlock, ipAddrBlocks),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IPList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAddrBlocks"
		},
};
static const int asn_MAP_ResourceBlock_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ResourceBlock_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ResourceBlock_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* asID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ipAddrBlocks */
};
asn_SEQUENCE_specifics_t asn_SPC_ResourceBlock_specs_1 = {
	sizeof(struct ResourceBlock),
	offsetof(struct ResourceBlock, _asn_ctx),
	asn_MAP_ResourceBlock_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ResourceBlock_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ResourceBlock = {
	"ResourceBlock",
	"ResourceBlock",
	&asn_OP_SEQUENCE,
	asn_DEF_ResourceBlock_tags_1,
	sizeof(asn_DEF_ResourceBlock_tags_1)
		/sizeof(asn_DEF_ResourceBlock_tags_1[0]), /* 1 */
	asn_DEF_ResourceBlock_tags_1,	/* Same as above */
	sizeof(asn_DEF_ResourceBlock_tags_1)
		/sizeof(asn_DEF_ResourceBlock_tags_1[0]), /* 1 */
	{ &asn_OER_type_ResourceBlock_constr_1, 0, SEQUENCE_constraint },
	asn_MBR_ResourceBlock_1,
	2,	/* Elements count */
	&asn_SPC_ResourceBlock_specs_1	/* Additional specs */
};

