/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_ResourceBlock_H_
#define	_ResourceBlock_H_


#include "asn1/asn1c/asn_application.h"

/* Including external dependencies */
#include "asn1/asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AsList;
struct IPList;

/* ResourceBlock */
typedef struct ResourceBlock {
	struct AsList	*asID	/* OPTIONAL */;
	struct IPList	*ipAddrBlocks	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceBlock_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceBlock;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceBlock_specs_1;
extern asn_TYPE_member_t asn_MBR_ResourceBlock_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AsList.h"
#include "IPList.h"

#endif	/* _ResourceBlock_H_ */
#include "asn1/asn1c/asn_internal.h"
