/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_RevocationInfoChoices_H_
#define	_RevocationInfoChoices_H_

#include "asn1/asn1c/RevocationInfoChoice.h"
#include "asn1/asn1c/asn_SET_OF.h"
#include "asn1/asn1c/constr_SET_OF.h"
#include "asn1/asn1c/constr_TYPE.h"

/* Forward declarations */
struct RevocationInfoChoice;

/* RevocationInfoChoices */
typedef struct RevocationInfoChoices {
	A_SET_OF(struct RevocationInfoChoice) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevocationInfoChoices_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevocationInfoChoices;
extern asn_SET_OF_specifics_t asn_SPC_RevocationInfoChoices_specs_1;
extern asn_TYPE_member_t asn_MBR_RevocationInfoChoices_1[1];

#endif	/* _RevocationInfoChoices_H_ */
