/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_RpkiSignedChecklist_H_
#define	_RpkiSignedChecklist_H_


#include "asn1/asn1c/asn_application.h"

/* Including external dependencies */
#include "asn1/asn1c/INTEGER.h"
#include "ResourceBlock.h"
#include "DigestAlgorithmIdentifier.h"
#include "asn1/asn1c/asn_SEQUENCE_OF.h"
#include "asn1/asn1c/constr_SEQUENCE_OF.h"
#include "asn1/asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileNameAndHash;

/* RpkiSignedChecklist */
typedef struct RpkiSignedChecklist {
	INTEGER_t	*version	/* DEFAULT 0 */;
	ResourceBlock_t	 resources;
	DigestAlgorithmIdentifier_t	 digestAlgorithm;
	struct RpkiSignedChecklist__checkList {
		A_SEQUENCE_OF(struct FileNameAndHash) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} checkList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RpkiSignedChecklist_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RpkiSignedChecklist;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileNameAndHash.h"

#endif	/* _RpkiSignedChecklist_H_ */
#include "asn1/asn1c/asn_internal.h"
