/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RpkiSignedChecklist-2021"
 * 	found in "draft-ietf-sidrops-rpki-rsc.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "RpkiSignedChecklist.h"

static int
memb_checkList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_checkList_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
static asn_oer_constraints_t asn_OER_memb_checkList_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..MAX)) */};
static int asn_DFL_2_cmp_0(const void *sptr) {
	const INTEGER_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	long value;
	if(asn_INTEGER2long(st, &value))
		return -1;
	return (value != 0);
}
static int asn_DFL_2_set_0(void **sptr) {
	INTEGER_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	return asn_long2INTEGER(st, 0);
}
static asn_TYPE_member_t asn_MBR_checkList_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FileNameAndHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_checkList_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_checkList_specs_5 = {
	sizeof(struct RpkiSignedChecklist__checkList),
	offsetof(struct RpkiSignedChecklist__checkList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_checkList_5 = {
	"checkList",
	"checkList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_checkList_tags_5,
	sizeof(asn_DEF_checkList_tags_5)
		/sizeof(asn_DEF_checkList_tags_5[0]), /* 1 */
	asn_DEF_checkList_tags_5,	/* Same as above */
	sizeof(asn_DEF_checkList_tags_5)
		/sizeof(asn_DEF_checkList_tags_5[0]), /* 1 */
	{ &asn_OER_type_checkList_constr_5, 0, SEQUENCE_OF_constraint },
	asn_MBR_checkList_5,
	1,	/* Single element */
	&asn_SPC_checkList_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RpkiSignedChecklist_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RpkiSignedChecklist, version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_2_set_0,	/* Set DEFAULT 0 */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpkiSignedChecklist, resources),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResourceBlock,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"resources"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpkiSignedChecklist, digestAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DigestAlgorithmIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"digestAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpkiSignedChecklist, checkList),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_checkList_5,
		0,
		{ &asn_OER_memb_checkList_constr_5, 0,  memb_checkList_constraint_1 },
		0, 0, /* No default value */
		"checkList"
		},
};
static const int asn_MAP_RpkiSignedChecklist_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_RpkiSignedChecklist_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RpkiSignedChecklist_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 2 }, /* resources */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 1 }, /* digestAlgorithm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -2, 0 }, /* checkList */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* version */
};
static asn_SEQUENCE_specifics_t asn_SPC_RpkiSignedChecklist_specs_1 = {
	sizeof(struct RpkiSignedChecklist),
	offsetof(struct RpkiSignedChecklist, _asn_ctx),
	asn_MAP_RpkiSignedChecklist_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RpkiSignedChecklist_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RpkiSignedChecklist = {
	"RpkiSignedChecklist",
	"RpkiSignedChecklist",
	&asn_OP_SEQUENCE,
	asn_DEF_RpkiSignedChecklist_tags_1,
	sizeof(asn_DEF_RpkiSignedChecklist_tags_1)
		/sizeof(asn_DEF_RpkiSignedChecklist_tags_1[0]), /* 1 */
	asn_DEF_RpkiSignedChecklist_tags_1,	/* Same as above */
	sizeof(asn_DEF_RpkiSignedChecklist_tags_1)
		/sizeof(asn_DEF_RpkiSignedChecklist_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RpkiSignedChecklist_1,
	4,	/* Elements count */
	&asn_SPC_RpkiSignedChecklist_specs_1	/* Additional specs */
};

