/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RsyncSpawnerChannel"
 * 	found in "rsync.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "asn1/asn1c/RsyncRequest.h"

static asn_TYPE_member_t asn_MBR_RsyncRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RsyncRequest, url),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"url"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RsyncRequest, path),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"path"
		},
};
static const ber_tlv_tag_t asn_DEF_RsyncRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RsyncRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 1 }, /* url */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 0 } /* path */
};
static asn_SEQUENCE_specifics_t asn_SPC_RsyncRequest_specs_1 = {
	sizeof(struct RsyncRequest),
	offsetof(struct RsyncRequest, _asn_ctx),
	asn_MAP_RsyncRequest_tag2el_1,
	2,	/* Count of tags in the map */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RsyncRequest = {
	"RsyncRequest",
	"RsyncRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_RsyncRequest_tags_1,
	sizeof(asn_DEF_RsyncRequest_tags_1)
		/sizeof(asn_DEF_RsyncRequest_tags_1[0]), /* 1 */
	asn_DEF_RsyncRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_RsyncRequest_tags_1)
		/sizeof(asn_DEF_RsyncRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RsyncRequest_1,
	2,	/* Elements count */
	&asn_SPC_RsyncRequest_specs_1	/* Additional specs */
};

int
RsyncRequest_init(struct RsyncRequest *req, char const *url, char const *path)
{
	memset(req, 0, sizeof(*req));
	if (OCTET_STRING_fromString(&req->url, url) < 0)
		return -1;
	if (OCTET_STRING_fromString(&req->path, path) < 0)
		return -1;
	return 0;
}
