/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RsyncSpawnerChannel"
 * 	found in "rsync.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_RsyncRequest_H_
#define	_RsyncRequest_H_

/* Including external dependencies */
#include "types/uri.h"
#include "asn1/asn1c/OCTET_STRING.h"
#include "asn1/asn1c/constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RsyncRequest */
typedef struct RsyncRequest {
	OCTET_STRING_t	 url;
	OCTET_STRING_t	 path;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RsyncRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RsyncRequest;

int RsyncRequest_init(struct RsyncRequest *, struct uri const *, char const *);

#ifdef __cplusplus
}
#endif

#endif	/* _RsyncRequest_H_ */
#include "asn1/asn1c/asn_internal.h"
