/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "rfc5652-12.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#include "asn1/asn1c/SignedAttributes.h"

static json_t *
SignedAttributes_encode_json(const struct asn_TYPE_descriptor_s *td,
    const void *sptr)
{
	json_t *result;
	const asn_anonymous_set_ *list;
	int i;

	if (!sptr)
		return json_null();

	result = json_object();
	if (result == NULL)
		return NULL;

	list = _A_CSET_FROM_VOID(sptr);
	td = &asn_DEF_CMSAttribute;

	for (i = 0; i < list->count; i++) {
		CMSAttribute_t *attr;
		json_t *node;
		char buf[OID_STR_MAXLEN];
		char const *key;

		attr = list->array[i];
		node = td->op->json_encoder(td, attr);
		if (node == NULL)
			goto fail;

		key = OBJECT_IDENTIFIER_to_string(&attr->attrType, buf);
		if (json_object_set_new(result, key, node) < 0)
			goto fail;
	}

	return result;

fail:	json_decref(result);
	return NULL;
}

asn_TYPE_operation_t asn_OP_SignedAttributes = {
	SET_OF_free,
	SET_OF_print,
	SET_OF_compare,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SignedAttributes_encode_json,
	SET_OF_encode_xer,
	0	/* Use generic outmost tag fetcher */
};

asn_TYPE_member_t asn_MBR_SignedAttributes_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CMSAttribute,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_SignedAttributes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
asn_SET_OF_specifics_t asn_SPC_SignedAttributes_specs_1 = {
	sizeof(struct SignedAttributes),
	offsetof(struct SignedAttributes, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_SignedAttributes = {
	"SignedAttributes",
	"SignedAttributes",
	&asn_OP_SignedAttributes,
	asn_DEF_SignedAttributes_tags_1,
	sizeof(asn_DEF_SignedAttributes_tags_1)
		/sizeof(asn_DEF_SignedAttributes_tags_1[0]), /* 1 */
	asn_DEF_SignedAttributes_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignedAttributes_tags_1)
		/sizeof(asn_DEF_SignedAttributes_tags_1[0]), /* 1 */
	{ NULL, 0, SET_OF_constraint },
	asn_MBR_SignedAttributes_1,
	1,	/* Single element */
	&asn_SPC_SignedAttributes_specs_1	/* Additional specs */
};
