/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc5280-a.1.asn1"
 * 	`asn1c -Werror -fcompound-names -fwide-types -D asn1/asn1c -no-gen-PER -no-gen-example`
 */

#ifndef	_Version_H_
#define	_Version_H_


#include "asn1/asn1c/asn_application.h"

/* Including external dependencies */
#include "asn1/asn1c/INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Version {
	Version_v1	= 0,
	Version_v2	= 1,
	Version_v3	= 2
} e_Version;

/* Version */
typedef INTEGER_t	 Version_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Version;
asn_struct_free_f Version_free;
asn_struct_print_f Version_print;
asn_constr_check_f Version_constraint;
ber_type_decoder_f Version_decode_ber;
der_type_encoder_f Version_encode_der;
xer_type_decoder_f Version_decode_xer;
xer_type_encoder_f Version_encode_xer;
oer_type_decoder_f Version_decode_oer;
oer_type_encoder_f Version_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Version_H_ */
#include "asn1/asn1c/asn_internal.h"
